version: "3"

services:
  xrpld:
    image: rippleci/xrpld:develop
    volumes:
      - ./.ci-config:/etc/opt/xrpld
    ports:
      - "5005:5005"
      - "6006:6006"
    command: ["--standalone"]
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          wget --quiet --tries=1 --post-data='{"method":"server_info","params":[{}]}'
          --header="Content-Type: application/json" -O /dev/null http://localhost:5005/ || exit 1
      interval: 5s
      timeout: 2s
      retries: 10
