version: "3"

services:
  xrpld:
    image: rippleci/xrpld:develop
    volumes:
      - ./.ci-config:/etc/opt/xrpld
    ports:
      - "5005:5005"
      - "6006:6006"
    command: ["--standalone"]
    healthcheck:
      test: ["CMD", "xrpld", "server_info"]
      interval: 5s
      timeout: 2s
      retries: 10
