//! Per-transaction-type proof verification.
//!
//! These are the safe counterparts to the [`crate::prove`] generators: each
//! function checks a proof against its public inputs and returns `Ok(())`
//! **iff** the proof is valid.
//!
//! | Function | Verifies | Generated by |
//! |---|---|---|
//! | [`convert`]         | [`ConvertProof`]     | [`prove::convert`](crate::prove::convert) |
//! | [`send`]            | [`SendProof`]        | [`prove::send`](crate::prove::send) |
//! | [`convert_back`]    | [`ConvertBackProof`] | [`prove::convert_back`](crate::prove::convert_back) |
//! | [`clawback`]        | [`ClawbackProof`]    | [`prove::clawback`](crate::prove::clawback) |
//! | [`revealed_amount`] | matching ciphertexts | — |
//!
//! Two lower-level range-proof checks — [`send_range_proof`] and
//! [`aggregated_bulletproof`] — are also exposed; the transaction-level
//! [`send`]/[`convert_back`] verifiers already cover these internally, so most
//! callers will not need them directly.
//!
//! # Return semantics
//!
//! Every verifier returns `Result<()>`:
//!
//! * `Ok(())` — the proof verified.
//! * `Err(_)` — verification failed. The underlying C contract returns the
//!   same non-zero status for *both* an algebraically-invalid proof **and**
//!   malformed input, so a verifier cannot distinguish the two; either way the
//!   correct response is to reject. Callers wanting a boolean can use
//!   [`Result::is_ok`].
//!
//! This "fail-closed" shape (anything other than a clean success is an `Err`)
//! is the same convention used by signature-verification APIs elsewhere in the
//! Rust ecosystem.

use crate::{
    Error, Result,
    prove::Participant,
    types::{
        BlindingFactor, Ciphertext, ClawbackProof, Commitment, ContextHash, ConvertBackProof,
        ConvertProof, Pubkey, SendProof,
    },
};
use mpt_crypto_sys as sys;

/// Length, in bytes, of the double-Bulletproof blob accepted by
/// [`send_range_proof`] (XLS-0096 §5.4).
const SEND_RANGE_PROOF_LEN: usize = 754;

/// Translate a safe [`Participant`] into the C ABI struct.
fn to_ffi(p: Participant<'_>) -> sys::mpt_confidential_participant {
    sys::mpt_confidential_participant {
        pubkey: *p.pubkey.as_bytes(),
        ciphertext: *p.ciphertext.as_bytes(),
    }
}

/// Map the C `0 = success / non-zero = failure` contract onto `Result`.
#[inline]
fn check(rc: i32) -> Result<()> {
    if rc == 0 {
        Ok(())
    } else {
        Err(Error::NonZeroRc(rc))
    }
}

// ─────────────────────────────────────────────────────────────────────────
//  Convert: 64-byte Schnorr Proof of Knowledge
// ─────────────────────────────────────────────────────────────────────────

/// Verifies a `ConfidentialMPTConvert` proof: that the holder knows the secret
/// key for `pubkey`, bound to `ctx`.
///
/// Re-deriving the Fiat-Shamir challenge from `pubkey` is what makes this
/// reject a proof presented against any *other* holder's public key.
pub fn convert(proof: &ConvertProof, pubkey: &Pubkey, ctx: &ContextHash) -> Result<()> {
    // SAFETY: 64-byte proof, 33-byte pubkey, 32-byte ctx hash match the FFI
    //         contract; all are read-only.
    let rc = unsafe {
        sys::mpt_verify_convert_proof(
            proof.as_bytes().as_ptr(),
            pubkey.as_bytes().as_ptr(),
            ctx.as_bytes().as_ptr(),
        )
    };
    check(rc)
}

// ─────────────────────────────────────────────────────────────────────────
//  ConvertBack: 816-byte composite
// ─────────────────────────────────────────────────────────────────────────

/// Inputs to [`convert_back`]. Mirrors the public half of
/// [`prove::ConvertBackProofParams`](crate::prove::ConvertBackProofParams) —
/// no secrets are needed to verify.
///
/// `balance_ciphertext` is the holder's on-ledger `CB_S`; `balance_commitment`
/// the Pedersen commitment carried in the transaction; `amount` the publicly
/// revealed withdrawal.
pub struct ConvertBackVerifyParams<'a> {
    pub proof: &'a ConvertBackProof,
    pub holder_pubkey: &'a Pubkey,
    pub balance_ciphertext: &'a Ciphertext,
    pub balance_commitment: &'a Commitment,
    pub amount: u64,
    pub context_hash: &'a ContextHash,
}

/// Verifies a `ConfidentialMPTConvertBack` proof: ownership of the balance,
/// commitment/ciphertext linkage, and a non-negative remainder
/// (`balance - amount >= 0`).
pub fn convert_back(p: ConvertBackVerifyParams<'_>) -> Result<()> {
    // SAFETY: 816-byte proof, 33-byte pubkey, 66-byte ciphertext, 33-byte
    //         commitment, 32-byte ctx hash match the FFI contract.
    let rc = unsafe {
        sys::mpt_verify_convert_back_proof(
            p.proof.as_bytes().as_ptr(),
            p.holder_pubkey.as_bytes().as_ptr(),
            p.balance_ciphertext.as_bytes().as_ptr(),
            p.balance_commitment.as_bytes().as_ptr(),
            p.amount,
            p.context_hash.as_bytes().as_ptr(),
        )
    };
    check(rc)
}

// ─────────────────────────────────────────────────────────────────────────
//  Send: 946-byte composite
// ─────────────────────────────────────────────────────────────────────────

/// Inputs to [`send`]. The participant list must be passed in the **same
/// order used when generating the proof** (sender, destination, issuer, then
/// optional auditor) — `participants[0]` is the sender.
pub struct SendVerifyParams<'a> {
    pub proof: &'a SendProof,
    pub sender: Participant<'a>,
    pub destination: Participant<'a>,
    pub issuer: Participant<'a>,
    pub auditor: Option<Participant<'a>>,
    /// The sender's on-ledger balance ciphertext (`CB_S`, `b1 || b2`).
    pub sender_spending_ciphertext: &'a Ciphertext,
    pub amount_commitment: &'a Commitment,
    pub balance_commitment: &'a Commitment,
    pub context_hash: &'a ContextHash,
}

/// Verifies a `ConfidentialMPTSend` proof across all participants.
pub fn send(p: SendVerifyParams<'_>) -> Result<()> {
    // Build the contiguous participant array the C side expects (≤ 4 entries),
    // matching the ordering in `prove::send`.
    let mut participants = [sys::mpt_confidential_participant {
        pubkey: [0; 33],
        ciphertext: [0; 66],
    }; 4];

    participants[0] = to_ffi(p.sender);
    participants[1] = to_ffi(p.destination);
    participants[2] = to_ffi(p.issuer);

    let n: u8 = if let Some(aud) = p.auditor {
        participants[3] = to_ffi(aud);
        4
    } else {
        3
    };

    // SAFETY: the participants array holds exactly `n` initialised entries and
    //         outlives the call; all other buffers match the FFI contract.
    let rc = unsafe {
        sys::mpt_verify_send_proof(
            p.proof.as_bytes().as_ptr(),
            participants.as_ptr(),
            n,
            p.sender_spending_ciphertext.as_bytes().as_ptr(),
            p.amount_commitment.as_bytes().as_ptr(),
            p.balance_commitment.as_bytes().as_ptr(),
            p.context_hash.as_bytes().as_ptr(),
        )
    };
    check(rc)
}

// ─────────────────────────────────────────────────────────────────────────
//  Clawback: 64-byte compact sigma proof
// ─────────────────────────────────────────────────────────────────────────

/// Verifies a `ConfidentialMPTClawback` proof: that `ciphertext` decrypts to
/// exactly `amount` under the issuer's secret key.
pub fn clawback(
    proof: &ClawbackProof,
    amount: u64,
    issuer_pubkey: &Pubkey,
    ciphertext: &Ciphertext,
    context_hash: &ContextHash,
) -> Result<()> {
    // SAFETY: 64-byte proof, 33-byte pubkey, 66-byte ciphertext, 32-byte ctx
    //         hash match the FFI contract.
    let rc = unsafe {
        sys::mpt_verify_clawback_proof(
            proof.as_bytes().as_ptr(),
            amount,
            issuer_pubkey.as_bytes().as_ptr(),
            ciphertext.as_bytes().as_ptr(),
            context_hash.as_bytes().as_ptr(),
        )
    };
    check(rc)
}

// ─────────────────────────────────────────────────────────────────────────
//  Revealed-amount consistency
// ─────────────────────────────────────────────────────────────────────────

/// Verifies that the holder's, issuer's and (optional) auditor's ciphertexts
/// all encrypt the same revealed `amount` under the shared ElGamal randomness
/// `blinding`.
pub fn revealed_amount(
    amount: u64,
    blinding: &BlindingFactor,
    holder: Participant<'_>,
    issuer: Participant<'_>,
    auditor: Option<Participant<'_>>,
) -> Result<()> {
    let holder_ffi = to_ffi(holder);
    let issuer_ffi = to_ffi(issuer);
    let auditor_ffi = auditor.map(to_ffi);

    // A null `auditor` pointer signals "no auditor" to the C side.
    let auditor_ptr = auditor_ffi
        .as_ref()
        .map_or(core::ptr::null(), |a| a as *const _);

    // SAFETY: `blinding` is 32 bytes; the three participant pointers either
    //         reference live stack values for the duration of the call or are
    //         null (auditor), as the contract permits.
    let rc = unsafe {
        sys::mpt_verify_revealed_amount(
            amount,
            blinding.as_bytes().as_ptr(),
            &holder_ffi,
            &issuer_ffi,
            auditor_ptr,
        )
    };
    check(rc)
}

// ─────────────────────────────────────────────────────────────────────────
//  Lower-level range-proof checks
// ─────────────────────────────────────────────────────────────────────────

/// Verifies the 754-byte double Bulletproof that bounds both the transfer
/// amount and the sender's remaining balance to `[0, 2^64)` (the range
/// component of a [`SendProof`]).
///
/// Returns [`Error::Invariant`] if `proof` is not exactly
/// `SEND_RANGE_PROOF_LEN` bytes — the C verifier reads a fixed-size buffer.
pub fn send_range_proof(
    proof: &[u8],
    amount_commitment: &Commitment,
    balance_commitment: &Commitment,
    context_hash: &ContextHash,
) -> Result<()> {
    if proof.len() != SEND_RANGE_PROOF_LEN {
        return Err(Error::Invariant("send range proof must be 754 bytes"));
    }
    // SAFETY: `proof` is verified to be exactly 754 bytes; commitments are
    //         33 bytes and the ctx hash 32 bytes per the FFI contract.
    let rc = unsafe {
        sys::mpt_verify_send_range_proof(
            proof.as_ptr(),
            amount_commitment.as_bytes().as_ptr(),
            balance_commitment.as_bytes().as_ptr(),
            context_hash.as_bytes().as_ptr(),
        )
    };
    check(rc)
}

/// Generic verifier for an aggregated Bulletproof over `commitments`.
///
/// Returns [`Error::Invariant`] if `commitments` is empty.
pub fn aggregated_bulletproof(
    proof: &[u8],
    commitments: &[Commitment],
    context_hash: &ContextHash,
) -> Result<()> {
    if commitments.is_empty() {
        return Err(Error::Invariant(
            "aggregated bulletproof needs at least one commitment",
        ));
    }
    // The C side takes an array of pointers to the 33-byte commitments.
    let mut ptrs: Vec<*const u8> = commitments.iter().map(|c| c.as_bytes().as_ptr()).collect();

    // SAFETY: `proof`/`proof_len` describe the same buffer; `ptrs` holds
    //         exactly `commitments.len()` valid pointers that outlive the
    //         call; the ctx hash is 32 bytes.
    let rc = unsafe {
        sys::mpt_verify_aggregated_bulletproof(
            proof.as_ptr(),
            proof.len(),
            ptrs.as_mut_ptr(),
            ptrs.len(),
            context_hash.as_bytes().as_ptr(),
        )
    };
    check(rc)
}
