#!/bin/sh
set -e

echo 'Running all pre-commit checks:'
cargo fmt -- --check
cargo clippy --all-features -- -D warnings
cargo test --release
cargo test --release --no-default-features --features embassy-rt,core,wallet,models,helpers,websocket,json-rpc
cargo doc --no-deps
cargo audit
