#!/usr/bin/env bash
# Regenerate src/bindings.rs from the vendored C headers.
#
# Requires bindgen-cli and libclang. Install bindgen-cli with:
#   cargo install bindgen-cli
#
# Downstream consumers of this crate do NOT need bindgen or libclang —
# `src/bindings.rs` is committed. Only maintainers run this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRATE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if ! command -v bindgen &> /dev/null; then
  echo "ERROR: bindgen CLI not found. Install with:" >&2
  echo "  cargo install bindgen-cli" >&2
  exit 1
fi

INCLUDE="$CRATE_ROOT/vendor/include"
OUT="$CRATE_ROOT/src/bindings.rs"

echo "==> Regenerating $OUT"

# Use a single-header shim (placed in vendor/include/ so clang resolves
# relative includes correctly) that #includes both public headers.
# bindgen parses this in one pass, producing bindings for both the
# primitive layer (secp256k1_mpt.h) and the utility layer (mpt_utility.h).
SHIM="$INCLUDE/_shim_all.h"
cat > "$SHIM" <<'EOF'
/* Autogenerated shim for bindgen. Do not commit. */
#include "secp256k1_mpt.h"
#include "utility/mpt_utility.h"
EOF
trap 'rm -f "$SHIM"' EXIT

bindgen \
  --allowlist-function 'secp256k1_.*|mpt_.*|generate_canonical_.*' \
  --allowlist-type     'mpt_.*|secp256k1_.*|account_id' \
  --allowlist-var      'SECP256K1_.*|kMPT_.*|tt[A-Z].*' \
  --output "$OUT" \
  "$SHIM" \
  -- -I"$INCLUDE"

# Prepend a generated-file warning header.
HEADER="// This file was generated by scripts/regenerate_bindings.sh.
// DO NOT EDIT BY HAND. Run that script to refresh after updating vendor/include.
// Upstream source: https://github.com/XRPLF/mpt-crypto
//
"
printf "%s%s" "$HEADER" "$(cat "$OUT")" > "$OUT"

echo "==> Done. $(wc -l < "$OUT") lines."
