on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

name: Unit

jobs:
  build_and_test:
    name: xrpl-rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build with default features
        run: cargo build --release
      - name: Build with no default features
        run: cargo build --release --no-default-features
      - name: Build for no_std
        run: cargo build --release --no-default-features --features embassy-rt,core,wallet,models,helpers,websocket,json-rpc
      - name: Build only core
        run: cargo build --release --no-default-features --features core
      - name: Build only wallet
        run: cargo build --release --no-default-features --features wallet
      - name: Build only models
        run: cargo build --release --no-default-features --features models
      - name: Build only helpers
        run: cargo build --release --no-default-features --features websocket,json-rpc,helpers,tokio-rt
      - name: Build only websocket
        run: cargo build --release --no-default-features --features websocket
      - name: Build only json-rpc
        run: cargo build --release --no-default-features --features json-rpc
      - name: Test with default features
        run: cargo test --release
      - name: Test for no_std
        run: cargo test --release --no-default-features --features embassy-rt,core,utils,wallet,models,helpers,websocket,json-rpc
